### ISSUE TITLE
Document Lacking on how to implement different resolver

### ISSUE THREAD

**Issue by oscarjaergren** [TinyStuff/TinyMvvm#20]
Hey, I don't want to use autofac cause it horrible perfomance compared to other IOCs but I cannot understand how to use the IResolver and create a new implementation.

Attempting to use TinyIOC as a container instead of autofac

**Comment by dhindrik** [comment]
https://www.nuget.org/packages/TinyMvvm.TinyIoC

https://danielhindrikes.se/index.php/2020/06/16/tinyioc-for-tinymvvm/
