### ISSUE TITLE
Use IViewModelBase instead of ViewModelBase

### ISSUE THREAD

**Issue by zleao** [TinyStuff/TinyMvvm#30]
It would be very nice if the `TinyMvvmViewCreator` triggered the `TinyMvvmSetup` for `IVewModelBase` instead of `ViewModelBase`. 

There are currently 2 places where the use of ViewModelBase is forced ([here](https://github.com/TinyStuff/TinyMvvm/blob/4b27013fd02cea62e760b3ab6aca9b83fbae34d7/src/TinyMvvm.Forms/TinyMvvmViewCreator.cs#L37) and [here](https://github.com/TinyStuff/TinyMvvm/blob/4b27013fd02cea62e760b3ab6aca9b83fbae34d7/src/TinyMvvm.Forms/TinyMvvmViewCreator.cs#L63))

From what I can see in the code, making the cast to `IViewModelBase` would not change any functionality in the framework and it would allow me/anyone to have it's how ViewModel implementmention and still be able to use this awesome framework!

Let me know your thoughts on it. I'm happy to make a PR, but I can see there's a 3.0 version comming, so maybe this could be added there?

I'm a long time 'user' of MvvmCross (contributed with a bit of code) and also written some extensions to use on top of it. I'm now using more often Xamarin.Forms, and feel that is time to make a switch :) 
I would however like to retain some of the approaches I have, specially in the ViewModel part and for that I would need to use my own ViewModel implementation, without inheriting from the `TiniMvvm.ViewModelBase`.

**Comment by dhindrik** [comment]
I have fixed this in the 3.0 branch. It will be out in 3.0.1-pre2.
