### ISSUE TITLE
Crash with Navigation Parameter

### ISSUE THREAD

**Issue by oscarjaergren** [TinyStuff/TinyMvvm#31]
```
        public override async Task Initialize()
        {
            IsBusy = true;

            await base.Initialize().ConfigureAwait(true);
            //await Task.Delay(5000);

            if (NavigationParameter is TabularScheduledItemViewModel job)
            {
                Job = job;
            }

            if (Job == null)
            {
                throw new ArgumentNullException(nameof(job));
            }
IsBusy = false;
}
```

How it is called

 ```
  private Task OnGoToJob(TabularScheduledItemViewModel job)
        {
            return Navigation.NavigateToAsync(nameof(JobPage), job);
        }




        public ICommand GoToJobCommand => new AsyncCommand<TabularScheduledItemViewModel>(OnGoToJob);

```
I'm a bit confused why this is happening. 
The parameter is null unless I add the Task.Delay, if I do, it loads perfectly. 
If not, Job gets null and crashes. 

Same thing if I cahnge the OnGoToJob to 

```
   private async Task OnGoToJob(TabularScheduledItemViewModel job)
        {
            await Navigation.NavigateToAsync(nameof(JobPage), job);
        }
```

I'm assuming this is some sort of async error somewhere, either by TinyMVVM or my usage.  
Only thing that seems to work is me using the Task.Delay there. 

Uses the TinyIOC Resolver if that is relevant.
AppShell. 

![image](https://user-images.githubusercontent.com/31920401/100459110-cd394700-30bc-11eb-88af-b5087535bc54.png)

**Comment by dhindrik** [comment]
Is it possible to share your setup code?
What version are you using?
Are you using the ShellNavigationHelper or the FormsNavigationHelper?

**Comment by oscarjaergren** [comment]
Sure, here's the init code. 
```
     /// <summary> TinyMVVM Initialisation code </summary>
        private static void InitTinyMvvm()
        {
            var navigationHelper = new ShellNavigationHelper();

            var currentAssembly = Assembly.GetExecutingAssembly();
            navigationHelper.RegisterViewsInAssembly(currentAssembly);

            TinyIoCContainer.Current.Register<INavigationHelper>(navigationHelper);

            foreach (var type in currentAssembly.ExportedTypes.Where(x => x.IsSubclassOf(typeof(ViewModelBase))))
            {
                TinyIoCContainer.Current.Register(type);
            }

            foreach (var type in currentAssembly.ExportedTypes.Where(x => x.IsSubclassOf(typeof(Page))))
            {
                TinyIoCContainer.Current.Register(type);
            }

            Resolver.SetResolver(new TinyIoCResolver());
        }
```



As you can see, using the latest pre release packages, version 3.0.1-pre2, but also tried this with the latest public version, same there.

**Comment by oscarjaergren** [comment]
I wonder if it can has anything to do with the item being sent. 
![image](https://user-images.githubusercontent.com/31920401/100629182-e6dac880-3320-11eb-94d3-14890eb4963c.png)

Going to test.

**Comment by oscarjaergren** [comment]
After much troubleshooting this has now been resolved.

The error was due to  x:TypeArgument not set on the page, and binding context set elsewhere.

**Comment by oscarjaergren** [comment]
Error still remains. 
Task.Delay is the only thing that eems to work to fix it at the moment. 

Closed earlier due to me thinking I solved it, nope. 
Just had still left the Task.Delay in the test.

**Comment by oscarjaergren** [comment]
![image](https://user-images.githubusercontent.com/31920401/100642351-9703fd80-3330-11eb-854d-0dde7c543e52.png)
One thing I think it might have to do with, is the namespaces.

I am using the Page Models naming convention for my pages models rather than the view model convention. 
Could that affect things?

**Comment by oscarjaergren** [comment]
If it helps, I keep getting 

TinyMvvm.ViewCreationException: 'The view 'JobDetailsPageModel?tinyid=000fe504-9b29-48b0-98dd-3852e3d63845, you're trying to navigate to has not been registered'

when I change the navigation to use viewmodel navigation.

**Comment by dhindrik** [comment]
Is JobDetailPage a view model base with JobDetailsPageModel as TypeArguments?

Maybe not related, but there is the other issue about when a Route is set to the same name as the view, https://github.com/TinyStuff/TinyMvvm/issues/26.

I will investigate and try to fix it. It will be part of the 3.0 release when it is done.

**Comment by oscarjaergren** [comment]
Just tried with the latest pre-release, 3.0.3.

It works now! 
So I think it might have been the same issue, or at least related.

**Comment by dhindrik** [comment]
You are welcome to reopen it if the problem returns.

**Comment by oscarjaergren** [comment]
So just some last minute information, cause I can now make the crash happen at will.
It wasn't related to the 3.0.3 update after all but rather about my async code, fear not. I did find a workaround. 
```

 public ICommand GoToJobCommand => new AsyncCommand<TabularScheduledItemViewModel>(OnGoToJob);

        private Task OnGoToJob(TabularScheduledItemViewModel job)
        {
            return Navigation.NavigateToAsync(nameof(JobDetailsPage), job);
        }
```

This works great, however. What caused the error was that I changed it to 


```
   private async Task OnGoToJob(TabularScheduledItemViewModel job)
        {
            var fullJob = await GetJobById(job).ConfigureAwait(false);

            await Navigation.NavigateToAsync(nameof(JobDetailsPage), fullJob).ConfigureAwait(false);
        }

```
Maybe I don't understand async code, or the AsyncCommand is broken (using the one from the pre-release of Xamarin community toolkit) But it made it call the Navigation method TWICE. So it created first a successful viewmodel then another one with a null parameter, weirded me out cause there was always 2 layers of pages for this. 

Might be worth investigating still, but I just worked around it by moving it the GetJobById method to the JobDetailsPage and the navigation code no longer caused any errors.
