### ISSUE TITLE
QueryParameters is null after navigation

### ISSUE THREAD

**Issue by Jabbah76** [TinyStuff/TinyMvvm#32]
I'm changing my app to implement TinyMvvm and I'm running into a problem: When I navigate to a viewmodel using a query parameter, the QueryParameters is always null.

Here's my code:

Viewmodel1, from where I'm navigating
```
MyCommand = new TinyCommand(OnMyCommand);

private async void OnMyCommand()
{
    string myValue = "test";
    await Navigation.NavigateToAsync($"{nameof(ViewModel2)}?param={myValue}");
}
```

In the destination viewmodel ViewModel2:
```
public class SetInfoViewModel : TinyMvvm.ViewModelBase
{
    public async override Task Initialize()
    {
        IsBusy = true;
        await base.Initialize();

        string myValue = QueryParameters["param"]; // QueryParameters is always null !!

        IsBusy = false;
    }
}
```

My App.xaml.cs:

Note that I'm using WindsorCastle's IoC container since I was already using that in my app.
```
public App()
{
    var navigationHelper = new TinyNavigationHelper.Forms.ShellNavigationHelper();
    var currentAssembly = Assembly.GetExecutingAssembly();
    navigationHelper.RegisterViewsInAssembly(currentAssembly);

    IocContainer.Instance.Register(Castle.MicroKernel.Registration.Component.For<TinyNavigationHelper.INavigationHelper>().Instance(navigationHelper));

    Resolver.SetResolver(new WIndsorResolver(IocContainer.Instance));
}
```

This is the installer for WindsorCastle:
```
    public class ViewModelInstaller : IWindsorInstaller
    {
        public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            container.Register(Classes.FromAssembly(GetType().Assembly)
                .BasedOn<TinyMvvm.ViewModelBase>().WithService.Self().LifestyleTransient());

            container.Register(Classes.FromAssembly(GetType().Assembly)
                .BasedOn<Xamarin.Forms.Page>().WithService.Self().LifestyleTransient());
        }
    }
```

Everything TinyMvvm related seems to work fine, except passing the parameters. Is this a bug or am I missing something?

PS: 'm using the latest stable release. I also tried upgrading to the latest 3.0.1 pre release but then I'm getting the error that it is unable to determine the route (parameter, uri).

**Comment by swittke** [comment]
I'm having the same issue with exact following the docs playbook.

**Comment by dhindrik** [comment]
There are some breaking changes to routes in 3.0. Not all pages are registered as routes anymore. ViewModels routes in registered if you use the Init method for it. Register all views as routes cause an exception if you used the same class name as the route name. As in the official Xamarin Shell sample for example.

What version of Xamarin.Forms are you using?

**Comment by Jabbah76** [comment]
I'm using the latest version of Xamarin.Forms: 4.8.0.1687

**Comment by themronion** [comment]
@dhindrik i am also getting null when getting the parameters, is there some additional setup i need to make? Note that the navigation completes successfully

**Comment by dhindrik** [comment]
Where in the ViewModel are you using the query parameters? 

Do you have some code that you can show me? Because last time I tried to reproduce it I was not able to do it.

**Comment by themronion** [comment]
I guess it has something to do with the way we put our ShellContent in AppShell and whether we call manually Routing.RegisterRoute(....), cause that's what i am doing. Here is some code, sorry for the mess there though, WIP. Check the WelcomePageViewModel and AuthorizationPageViewMod
[ExpressTaxi.zip](https://github.com/TinyStuff/TinyMvvm/files/7598455/ExpressTaxi.zip)
el

**Comment by themronion** [comment]
@dhindrik here is the sample from the wiki, same problem even after i added ```navigationHelper.InitViewModelNavigation(...);```
[TinyMVVMTest.zip](https://github.com/TinyStuff/TinyMvvm/files/7608305/TinyMVVMTest.zip)

**Comment by themronion** [comment]
@dhindrik I finally managed to understand what is the cause of this after checking the source code. When using Shell all pages must inherit from ShellViewBase and not just regular ViewBase. Probably it is worth to point this out in the docs

**Comment by dhindrik** [comment]
Yes, I definitely have to add that. Thank you!

**Comment by dhindrik** [comment]
Docs are now updated.
