### ISSUE TITLE
Using Nullable Code Style Causes Crash with TinyMVVM

### ISSUE THREAD

**Issue by oscarjaergren** [TinyStuff/TinyMvvm#33]
Found an interesting bug causing TinyMVVM not to be able to find the ViewModel when changing to nullableTypes. 

Having this, for some reason causes the viewmodel locator inside TinyMVVM to not find it. 

       
```
private string? _formsEndpoint ;


   public string FormsEndpoint
        {
            get => _formsEndpoint ?? throw new InvalidOperationException("Uninitialized property: " + nameof(FormsEndpoint));
            set => Set(ref _formsEndpoint, value);
        }

```
This sample has excluded the FormsEndPoint being set in the constructor 

However, this works fine.

 ```
 private string _formsEndpoint;

  public string FormsEndpoint
        {
            get => _formsEndpoint;
            set
            {
                _formsEndpoint = value;
                RaisePropertyChanged();
            }
        }
```

**Comment by oscarjaergren** [comment]
Note that this seems to be the recommended way to use these properties.

![image](https://user-images.githubusercontent.com/31920401/101191473-a0070e80-3651-11eb-8570-1790f5d82f1a.png)


https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types

**Comment by dhindrik** [comment]
What version of TinyMvvm are you using and what version of Xamarin.Forms?

**Comment by dhindrik** [comment]
What is the stracktrace from the crash? 

Do it work in a non-TinyMvvm app? I guess Xamarin.Forms maybe not can handle the exception?

**Comment by dhindrik** [comment]
I have investigated, debugged, and talked to a couple of people. The way you do it is best-practice for C# as you say, but in a ViewModel for Xamarin.Forms it will not work because the binding engine can not handle it.

**Comment by oscarjaergren** [comment]
Sorry for slow response, office has closed during the holidays and haven't been working on this the last week. 
However, this aint critical in any way, but mind telling me a more about 'ViewModel for Xamarin.Forms it will not work because the binding engine can not handle it.' Just curious about the binding engine and why it doesn't work, will this error happen for any MVVM patterns one use? 

Nothing important, just curious
