### ISSUE TITLE
[Request] Add CanResolve or IsRegistered to TinnyMvvm.IoC.IResolver

### ISSUE THREAD

**Issue by zleao** [TinyStuff/TinyMvvm#34]
It would be a 'nice-to-have' feature. 
I could try to resolve a type and catch the exception but, in my opinion, a more elegant solution would be to have either:
- `CanResolve(Type)` and `CanResolve<T>()`
OR
- `IsRegistered(Type)` and `IsRegistered<T>()`

**Comment by dhindrik** [comment]
What do think about the way I implemented it in PR #35?

**Comment by zleao** [comment]
I works for me and the approach makes sense!
Thank you for taking a look so fast!

**Comment by zleao** [comment]
Do you have an idea when is this implementation going to be available in a nuget package?

**Comment by dhindrik** [comment]
Will trigger a new 3.0 release now.
