### ISSUE TITLE
NavigationParamter is always null

### ISSUE THREAD

**Issue by BenBtg** [TinyStuff/TinyMvvm#42]
Using latest preview version of TinyMvvm(3.0.1-pre7) and Xamarin.Forms(5.0.0.2012)

All views and ViewModels are registered. 
ShellNavigationHelper works but NavigationParameter is always null.

**Comment by dhindrik** [comment]
Thank you for reporting.

Where are you checking for the value?

**Comment by dhindrik** [comment]
@BenBtg  do you have more info?

**Comment by themronion** [comment]
@dhindrik repro is there #32

**Comment by dhindrik** [comment]
This will maybe also be solved with ShellViewBase as #32 ?

**Comment by themronion** [comment]
@dhindrik yeap
