### ISSUE TITLE
FlyoutPage not supported

### ISSUE THREAD

**Issue by janwiebe-jump** [TinyStuff/TinyMvvm#49]
Hi,
I am using the FormsNavigationHelper with a FlyoutPage as my root layout, and it looks like this is not supported. When trying to navigate inside a Detail page (That wraps a ViewBase in the NavigationPage), the navigation is not working.
On Android I get an error that global navigation is not supported.

I can make a PR to add FlyoutPage support if you like.

**Comment by dhindrik** [comment]
Yes, it is not updated since they renamed the control. 

You are welcome to create a PR.
