### ISSUE TITLE
Add navigation with arguments

### ISSUE THREAD

**Issue by johankson** [TinyStuff/TinyMvvm#6]
Add the possibility to pass arguments when navigating. The pattern needs to coexist with IoC and dependency injection in the constructor.

# Suggestion 1

Add a key value storage to the ViewModelBase called Params that is a dictionary of string and string. after navigation to a new view the view model is prepped with params from the navigation and accessible using the following code:

```csharp
public MyViewModel(IInjectedService anyService)
{
    var param = params["MyParam"];
}
```

PROS: It's easy to understand
CONS: It hides functionality that is hard to replace in the ViewModelBase.

# Suggestion 2

We pass in a params service that can be used if needed.

```sharp
public MyViewModel(IInjectedService anyService, IParams parameters)
{
    var param = parameters["MyParam"];
}
```

PROS: It doesn't hide functionality in the ViewModelBase class
CONS: Harder to understand and more code to type

# Other thinks to think about

We need to make changes to TinyNavigationHelper in order to support the scenarios above.

**Comment by dhindrik** [comment]
This is implemented with the ShellNavigationHelper.
