### ISSUE TITLE
NavigationExtensions for navigating to Forms pages

### ISSUE THREAD

**Issue by johankson** [TinyStuff/TinyMvvm#7]
Is it possible to add a navigation extension to INavigationHelper so that we in a forms environment can support navigating to already instantiated views?

```csharp
// Something like this
var view = Resolver.Resolve<MyView>();
view.SomeMethod();  // Sometimes you want to do something to the view before displaying it
await Navigation.NavigateToAsync(view);
```

1. Is it a bad idea?
2. Can we work around this somehow? Write code that works with the current API?
3. Are extensions methods the way to go?

**Comment by dhindrik** [comment]
It's a good it's a good idea to have it as an extension if we implement it, but it's a bad idea because your ViewModels will not work if you want to add a new platform with not is Xamarin.Forms.

**Comment by dhindrik** [comment]
Implemented by @johankson in this commit. https://github.com/dhindrik/TinyNavigationHelper/commit/af36db9f7ef255dd6bcd84102618ea77947c5fe2
